### ISSUE TITLE
How long does it take to inference an image?

### ISSUE THREAD

**Issue by 121649982** [ZiweiWangTHU/BiDet#1]
请问一下识别一张图像，耗时多少呢？

**Comment by Wuziyi616** [comment]
Hi, thank you for your attention about our work! Although this paper focuses on efficient detection, we don't conduct experiments on real hardwares like FPGAs because we think it's out of the scope of our work. Therefore, we don't have fps or other results about the time used to detect one image.

Besides, we compute the FLOPs and #Params of our BiDet detection frameworks to demonstrate its effectiveness. And the superiority of BNN guarantees its high speed. For actual timing, I think you can refer to other papers that conduct experiments on hardwares like [IR-Net](https://arxiv.org/pdf/1909.10788.pdf) and [BBG-Net](https://arxiv.org/pdf/1909.12117.pdf).
