### ISSUE TITLE
runtimeError: Errors in loading state_dict for module list

### ISSUE THREAD

**Issue by youngboy52** [ZiweiWangTHU/BiDet#12]
Hi, I have trouble in loading pretrained vgg model, and met the problem as follows:
![image](https://user-images.githubusercontent.com/15629424/91932262-3f95c780-ed18-11ea-8a8d-9b3b6acd7a76.png)

My environment configs: python 3.5.6, torch 0.4.0. Are there some wrongs in my configs? could you tell me your configs or corresponding solutions? Looking forward to your reply!

**Comment by Wuziyi616** [comment]
Hi! Thank you for your attention to our work. Yes, that's truly an environment problem. Actually in pytorch>=1.0, BN has one more parameter *num_batches_tracked* compared with the version before (for example pytorch 0.4.0 you're using). And the pre-trained weight I provide is trained using pytorch 1.0.1 and that's why you can't load in pytorch 0.4.0. I think you can solve this issue by simply updating pytorch to 1.0 or higher version.

**Comment by youngboy52** [comment]
Thank you for your quick reply, I solved this problem via your suggestion!
