### ISSUE TITLE
About DoReFa-Net

### ISSUE THREAD

**Issue by SteveTsui** [ZiweiWangTHU/BiDet#15]
How did you get the FLOPs about DoReFa-Net, 4694M？ What is the calculating rule？

**Comment by Wuziyi616** [comment]
Hi! Thank you for your interest in our work. All the FLOPs and #Params in our paper is calculated by a PyTorch package called [pytorch-OpCounter](https://github.com/Lyken17/pytorch-OpCounter). You can easily use it to get the results we reported in the paper. BTW, in order to calculate for DoReFa-Net (and also TWN), you need to register custom layers and define their FLOPs as described in their README file. Since we use 4-bit quantization for both network weights and activations, we simply define the FLOPs for a DoReFa-Conv layer to be 1/8 of a full-precision Conv layer.
