### ISSUE TITLE
Model Binarized Problem

### ISSUE THREAD

**Issue by Zeshengx** [ZiweiWangTHU/BiDet#17]
Hi, I am trying to repeat the experiment in your paper, and meeting some problems in training part. I use the recommended command [python ssd/train_bidet_ssd.py --dataset="VOC" --data_root="D:\01DL\data\VOCdevkit" --basenet="D:\01DL\BiDet-master\ssd\pretrain\vgg16.pth"] to run the training and get the final model saved as " VOC_final.pth". However, the "VOC_final.pth", which I think is the parameters of the trained "BiDet_SSD model", is around 127MB. According to the paper, the output binary model should be around 20MB, since "bidet_ssd" build in bidet_ssd.py. I am confused whether I followed the incorrect way to run your code or missed any parameter setting. 
In the test part, I got TypeError as follow:
![ssd_voc_eval1](https://user-images.githubusercontent.com/11968870/98492232-2eb28680-2272-11eb-8d6a-e9668b19ab73.PNG)
Hoping for your response, thanks.

**Comment by Wuziyi616** [comment]
Hi! Thank you for your interest in our work! For the first question, I think you can refer to this issue #13 for the answer. To be brief, the saved weight (those state_dicts) still contain **float-valued** parameters because PyTorch doesn't support binary-value operations. Also, if you want to binarize the weight, you need to follow BiReal-Net to fix model weight and re-train BN layers to absorb the scaling factor.

For the second question, well, that's strange, I don't encounter such problem using the code. I guess it may be related to the PyTorch version you used. I recommend you use torch>=1.0. Also, you can use pdb to try to debug it, I don't think it is a big problem. If none of these helps, tell me and I will look into it and figure it out later.

**Comment by Zeshengx** [comment]
Actually, the second problem botherd me for several days.  I use torch 1.7.0, and when I run the inital "eval_voc.py", I get the RuntimeError：Legacy autograd function with non-static forward method is deprecated.
![ssd_voc_eval2](https://user-images.githubusercontent.com/11968870/98511332-80bdd100-229f-11eb-8158-25563a3de71e.PNG)
I fixed it by adding "@staticmethod" on forward() in bidet_ssd.py. Then, the error I mentioned before just trigged.
![bidet_ssd1](https://user-images.githubusercontent.com/11968870/98511507-be225e80-229f-11eb-97cb-1ad38d916f31.PNG)
I am wondering if you have a trained bidet_ssd.pth, so I can check whether the error is caused by my training model or the other reasons with torch version.

**Comment by Wuziyi616** [comment]
Hi! I am quite sure this is caused by PyTorch version. You can switch to for example torch1.2.0 and my original code will be OK.

On the other hand, if you want to set some function to be **staticmethod** in python, you also need to delete the "self" in its input parameter list (def forward(self, x) --> def forward(x)).

In addition, actually the error in the first image you post is related to [this line](https://github.com/ZiweiWangTHU/BiDet/blob/master/ssd/bidet_ssd.py#L205). So you should add "@staticmethod" [here](https://github.com/ZiweiWangTHU/BiDet/blob/master/ssd/layers/functions/detection.py#L8). As you can see the error message points to "line 206, output = self.predict(", and self.detect is a function imported from ssd/layers/functions/detection.py.

**Comment by Wuziyi616** [comment]
BTW about the pretrained BiDet weight, I didn't notice that I forgot to upload them! It's embarrassed that I didn't discover this after half a year, and I really apologize for this. I will managed to upload the pretrained weight of SSD and Faster R-CNN that can reproduce the mAP reported in the paper to this repo soon. (But you know, after CVPR and ICLR rebuttal DDL)

**Comment by Zeshengx** [comment]
Thanks for your advise. I figured out the pytorch version problem by referring https://github.com/amdegroot/ssd.pytorch/issues/444.
I made some changes in ssd/bidet_ssd.py and ssd/layers/functions/detection.py, and it works for me on pytorch 1.7.0.

[changes-pytorch1.7.0.zip](https://github.com/ZiweiWangTHU/BiDet/files/5527965/changes-pytorch1.7.0.zip)

**Comment by Wuziyi616** [comment]
Sure! Thank you for your effort, I think I need to mention this in the README file of this repo. Thank you very much for figuring it out!
