### ISSUE TITLE
1*1 conv & 3*3 conv 

### ISSUE THREAD

**Issue by puhan123** [ZiweiWangTHU/BiDet#21]
Hello! Would you like to discuss three questions with me? Thank you.

Did you discover that BinaryConv for 1*1conv perform poorly in the detection task?

Are binary 11 conv or binary 33 the same for object task?

The Bi-det method is suitable for Yolo_v3?

**Comment by Wuziyi616** [comment]
Sure. Though I haven't been working on this for a while, I will try my best to discuss with you.

For the first question. Yes, 1x1 BinConv performs very poorly. That's why I keep the 1x1 Conv full-precision in SSD [here](https://github.com/ZiweiWangTHU/BiDet/blob/master/ssd/bidet_ssd.py#L72) because I discovered that binarizing it will degrade the performance significantly. However strangly, binarizing the 1x1 Conv [here](https://github.com/ZiweiWangTHU/BiDet/blob/master/ssd/bidet_ssd.py#L237-L243) (in the detection head) has small impact on the detection performance. I am not sure why.

For the second question. What do you mean by "binary 11" and "binary 33"? Do you mean binary 1x1/3x3 Conv? Also what do you mean by "object task"? Sorry that I don't really understand this question.

For the third question. Well, I am not sure. I think you can simply replace all the Conv layers in YOLOV3 and have a try. One thing I should mention is that, YOLOV3 uses DarkNet with many 1x1 Conv (similiar to the bottleneck structure in ResNet). In our BNN image classification experiments, binarizing bottleneck harms the accuracy greatly, and I think that's why most BNN papers only report accuracy on ResNet-18 and ResNet-34 because they don't have bottlenecks. One possible solution is that you just keep these 1x1 Conv full-precision because they only increase small computation and FLOPs overhead.

**Comment by puhan123** [comment]
Thank you very much! 
You are so nice!
It help me a lot!
