### ISSUE TITLE
The code about information bottleneck

### ISSUE THREAD

**Issue by puhan123** [ZiweiWangTHU/BiDet#22]
The code of information bottleneeck is as below:
![image](https://user-images.githubusercontent.com/24897773/107113725-b7ee4f00-689b-11eb-8ff0-1834a33cd561.png)
Why it is not same as the formula J1?
![image](https://user-images.githubusercontent.com/24897773/107113769-07347f80-689c-11eb-84c1-dcf5e5fd61d6.png)
Do I understand you correctly? Thank you very much!

**Comment by Wuziyi616** [comment]
Well, you are right the formulation is not the same. Note that loss_r is only the I(X; F) term in the IB objective, which is the former part of J1. You can, of course, use the log probability as in J1 to compute the loss, but in practice (I guess this is a tradition in DL era), we often use simpler loss to approximate it. That's why I use the L2 norm of the feature maps.

Intuitively speaking, we use standard Normal distribution as the prior of feature maps ($ p( f_{st} ) $), and minimizing $ p( f_{st} | x ) / p( f_{st} ) $ is the same as forcing the predicted mean ($ p( f_{st} | x ) $) to be close to 0. So minimizing the L2 norm of feature maps can achieve this goal.

For the later part of J1, it is achieved as the traditional detection loss [here](https://github.com/ZiweiWangTHU/BiDet/blob/master/ssd/train_bidet_ssd.py#L232). So the IB loss J1 = loss_l + loss_c + loss_r.
