### ISSUE TITLE
The code of Auto-Bidet

### ISSUE THREAD

**Issue by puhan123** [ZiweiWangTHU/BiDet#28]
Do you have any plans to release the code of the Auto-Bidet?
 I'm very interested in it!
 Thank you very much!

**Comment by Wuziyi616** [comment]
We don't have any plan to release the code in the near future mainly because of three folds:
- I am no longer in that lab, and the code & pre-trained weights are on the server which I have no access to now
- We have applied for a patent using this paper. So I am not sure if I have the right to open source the code
- I am busy with my graduation and other projects recently. So I may not have time to clean the code

I will let you know if we are able to release the code in the future :)

**Comment by puhan123** [comment]
OK,Thank you very much for your reply!
